# Generated by Django 5.2.8 on 2025-11-28 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_chead0_blogpost_chead1_blogpost_chead2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Blogpost',
            old_name='blog_id',
            new_name='post_id',
        ),
    ]
