# Generated by Django 5.2.8 on 2025-11-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Contact',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='Contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='Contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='Contact',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
