# Generated by Django 5.2.8 on 2025-11-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_contact_desc_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('zip_code', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='Contact',
            name='id',
        ),
        migrations.AddField(
            model_name='Contact',
            name='msg_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
