# Generated by Django 5.2.8 on 2025-11-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amout',
            field=models.IntegerField(default=0),
        ),
    ]
