# Generated by Django 5.2.8 on 2025-11-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orders_amout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='amout',
            new_name='amount',
        ),
    ]
