# Generated by Django 5.2.8 on 2025-12-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_amout_orders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='country',
            field=models.CharField(default='', max_length=500),
        ),
    ]
